### ISSUE TITLE
As a user I want to be able to create a profile

### ISSUE THREAD

**Issue by c-w** [yunity/yunity-core#7] opened 2015-09-24 18:28 UTC

**Comment by neeljp** [comment] 2015-09-26 08:55
Closed as an duplicate of https://github.com/yunity/yunity/issues/6

**Comment by Sliverriver** [comment] 2015-10-04 10:43
my Profile would include : my Home location,  my date of birth, twitter, github, tox-id, short description of oneself that is publicly available.

**Comment by tiltec** [comment] 2016-03-18 22:26
#19 describes the same topic and has more information. Closing.

**Comment by tiltec** [comment] 2016-03-18 22:28
Sorry, was confused. This card is about the whole profile:
https://trello.com/c/d6p44LvP/52-u-2-as-a-user-i-want-to-view-and-edit-my-profile-so-that-i-can-tell-something-about-me-story-points

**Closed** 2016-06-22 19:45 UTC
Labels: implementation, user-story
